### ISSUE TITLE
Request: Make delays configurable

### ISSUE THREAD

**Issue by ghost** [poelstra/arduino-multi-button#6]
It would be nice to be able to set the short/long/double click delays in the setup() for example.

**Comment by poelstra** [comment]
Agreed.

Not sure what the best approach is, I'd like to prevent adding these timeouts to each instance of a button, so perhaps the existing static properties would need to be made publicly changeable.

If you'd like to give that a go, I'll be happy to merge a PR, otherwise I'll leave it as a reminder to fix whenever I'll get to it (which may take a while).

**Comment by Fossil01** [comment]
I am very new to C++. It seemed simple to make it a public property but tried to make it work on my machine but I couldn't get it to function :-)

It would also be nice to have the option to set delays per button. But not necessary for my current project.

**Comment by poelstra** [comment]
No worries, I'll just leave it as an enhancement request. I'll revisit it on my next Arduino-with-a-button project ;)

**Comment by tcarney57** [comment]
I've addressed this issue in the short run simply by changing the static properties:

`private:
    static const int DEBOUNCE_DELAY    =  20; // ms
    static const int SINGLECLICK_DELAY = 250; // ms
    static const int LONGCLICK_DELAY   = 1000; // ms`

I changed LONGCLICK_DELAY to 1000ms. 350ms was too short for my purposes.

**Comment by jakovkolesnik** [comment]
Thanks for the neat library Martin,
I needed external dynamic configuration for double click delay so created a fork for that purpose.
https://github.com/jakovkolesnik/arduino-multi-button-config

Please feel free to use if you like the approach.

**Comment by poelstra** [comment]
Closed via #13.

Thanks @jakovkolesnik!
